/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/125k.fa
/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/250k.fa
/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/500k.fa
/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/1000k.fa
/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/1500k.fa
/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/2000k.fa
/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/2500k.fa
/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/3000k.fa
/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/3500k.fa
/usr/bin/time -v ./index -z 8 -o out -m 0 -t ../../data/4000k.fa
